blue/urls.py
from django.urls import path
from .views import *

app_name = 'blue'

urlpatterns = [
    path('profil', profil, name='profil'),
    path('editProfilPengunjung', editProfilPengunjung, name='editProfilPengunjung'),
    path('editProfilIndividu', editProfilIndividu, name='editProfilIndividu'),
    path('editProfilPerusahaan', editProfilPerusahaan, name='editProfilPerusahaan'),
    path('dompetDigital', dompetDigital, name='dompetDigital'),
    path('tambahSaldo', tambahSaldo, name='tambahSaldo'),
]

event/urls.py
from django.urls import path
from .views import *

app_name = 'event'

urlpatterns = [
    path('', daftar_event, name='daftar_event'),
    path('my_event', my_event, name='my_event'),
    path('create/', create, name='create_event'),
    path('update/<str:id>/', update, name='update_event'),
    path('delete/<str:id>/', delete, name='delete_event'),
    path('deleteconfirm/<str:id>/',confirmDelete, name='confirm_delete'),
    path('getLokasi/<str:id>/', getLokasi, name='get_lokasi'),
    path('getKelasTiket/<str:id>/', getKelasTiket, name='get_kelas_tiket')
]

eventplus/urls.py
from django.contrib import admin
from django.urls import path, include
from user.views import *
from landingpage.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('registerpengunjung/', registerPengunjung, name='register_pengunjung'),
    path('registerorganizer/', registerOrganizer, name='register_organizer'),
    path('transaksi/', include('transaksi.urls')),
    path('testimoni/', include('testimoni.urls')),
    path('', include('event.urls')),
    path('pesanan/', include('pesanan.urls')),
    path('blue/', include('blue.urls')),
]

pesanan/urls.py
from django.urls import path
from . import views

app_name = 'pesanan'

urlpatterns = [
	path('', views.pesan_tiket_view, name='pesan_tiket'),
	path('add/<str:pk>/', views.add_daftar_tiket_view, name='add_daftar_tiket'),
	path('delete/<str:pk>/', views.delete_daftar_tiket_view, name='delete_daftar_tiket'),
	path('buat/<str:pk>/', views.buat_transaksi_view, name='buat_transaksi'),
	path('cancel/<str:pk>/', views.cancel_pesan_tiket_view, name='cancel_pesan_tiket'),
	path('transaksi_saya/', views.transaksi_saya_view, name='transaksi_saya'),
	path('transaksi_saya/edit/<str:pk>/', views.edit_transaksi_view, name='edit_transaksi'),
	path('transaksi_saya/delete/<str:pk>/', views.delete_transaksi_view, name='delete_transaksi'),
]

event/models.py
from django.db import models

# Create your models here.

event/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.http import JsonResponse
from .connection import *
from datetime import datetime
from .form import *

# Create your views here.
def daftar_event(request):
    if request.GET.get('q'):
        event = search(request.GET['q'])
    else:    
        event = daftarEvent()
    paginator = Paginator(event, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    role = None
    email = None
    auth = False
    if request.session.get('user_email'):
        role = request.session['role']
        email = request.session['user_email']
        auth = True
    context = {
        'auth':auth,
        'page':page_obj,
        'role':role,
        'email':email,
        'time':datetime.now()
    }

    return render(request, 'event/daftar_event.html', context)

def my_event(request):
    if not (request.session['user_email'] or request.session['role']=='Pengunjung'):
        return redirect('/')
    
    event = myEvent(request.session['user_email'])
    context = {
        'auth':True,
        'role':request.session['role'],
        'event':event,
        'time':datetime.now()
    }
    return render(request, 'event/my_event.html', context)

def create(request):
    if not (request.session['user_email'] or request.session['role']=='Pengunjung'):
        return redirect('/')

    form = UpdateEvent(request.POST or None)
    lokasiFormSet = LokasiEventSet(request.POST or None)
    kelasTiketFormSet = kelasTiketEvent(request.POST or None)
    context = {
        'auth':True,
        'role':request.session['role'],
        'form':form,
        'lokasiForm':lokasiFormSet,
        'kelasTiketForm':kelasTiketFormSet,
    }

    if request.method=='POST' and form.is_valid():
        createEvent(form.cleaned_data, request.session['user_email'])
        return redirect('/event/my_event')
    return render(request, 'event/create1.html', context)

def update(request, id):
    if not (request.session['user_email'] or request.session['role']=='Pengunjung'):
        return redirect('/')
    event = currentEvent(id)
    tema = temaEvent(id)
    listTema = []
    for t in tema:
        listTema.append(''.join(t))
    form = UpdateEvent(request.POST or None, initial= {
        'nama':event[1],
        'tanggal_mulai':event[2],
        'tanggal_selesai':event[3],
        'jam_mulai':event[4],
        'jam_selesai':event[5],
        'desc':event[6],
        'tipe':event[9],
        'tema':listTema,
    })
    context = {
        'auth':True,
        'role':request.session['role'],
        'form':form,
        'id':id
    }
 
    if request.method=='POST':
        a = request.POST.getlist('dataKelasTiket[]')
        b = request.POST.getlist('dataGedung[]')
        print(request.POST.__dict__)
        c = {
            'nama':request.POST['nama'],
            'tanggal_mulai':request.POST['tanggal_mulai'],
            'tanggal_selesai':request.POST['tanggal_selesai'],
            'jam_mulai':request.POST['jam_mulai'],
            'jam_selesai':request.POST['jam_selesai'],
            'desc':request.POST['desc'],
            'tipe':request.POST['tipe']
        }
        print('test')
        print(a)
        print(b)
        print(c)
        updateEvent(c, id)

        return redirect('/event/my_event')
    return render(request, 'event/update.html', context)

def delete(request, id):
    if not (request.session['user_email'] or request.session['role']=='Pengunjung'):
        return redirect('/')

    context = {
        'auth':True,
        'role':request.session['role'],
        'id':id
    }
    return render(request, 'event/delete.html', context)

def confirmDelete(request, id):
    if not (request.session['user_email'] or request.session['role']=='Pengunjung'):
        return redirect('/')
        
    deleteEvent(id)
    return redirect('/')

def getLokasi(request, id):
    lokasi = lokasiEvent(id)
    arrDict = []
    for l in lokasi:
        arrDict.append({
            'nama_gedung':l.nama_gedung,
            'kota':l.kota,
            'alamat':l.alamat
        })
    dataDict = {'data':arrDict}
    return JsonResponse(dataDict)

def getKelasTiket(request, id):
    kelasTiket = kelasTiketEvent(id)
    arrDict = []
    for kt in kelasTiket:
        arrDict.append({
            'nama_kelas':kt.nama_kelas,
            'tarif':kt.tarif,
            'kapasitas':kt.kapasitas
        })
    dataDict = {'data':arrDict}
    return JsonResponse(dataDict)

event/templates/event/create.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %} 

{% block title %}Create Event{% endblock title %}
{% block content %}
<h1 class="text-center">Buat Event</h1>
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <table class="table table-light table-striped formContainerGedung">
        <tr>
            <th>Nama Gedung</th>
            <th>Kota</th>
            <th>Alamat</th>
        </tr>
        {% for form in kelasTiketForm %}
        <tr>
            <td>{{ form.nama_kelas }}</td>
            <td>{{ form.tarif }}</td>
            <td>{{ form.kapasitas }}</td>
        </tr>
        {% endfor %}
    </table>
    <a href="#" class="tambah-gedung">Tambah Row</a>
    <button type='submit'>Create</button>
    <a href="{% url 'event:daftar_event' %}">Cancel</a>
</form>
{% endblock content %}

{% block script %}

{% endblock script %}

event/templates/event/create1.html
{% extends 'base.html' %}

{% load crispy_forms_tags %} 

{% block title %}Create Event{% endblock title %}

{% block content %}
<h1 class="text-center">Create Event</h1>
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <p>Lokasi</p>
    <table class="table table-light table-striped formContainerGedung">
        <tr>
            <th>Nama Gedung</th>
            <th>Kota</th>
            <th>Alamat</th>
            <th>Hapus</th>
        </tr>
    </table>
    <button class="tambah-gedung">Tambah</button>
    
    <p>Kelas Tiket</p>
    <table class="table table-light table-striped formContainerKelasTiket">
        <tr>
            <th>Nama Kelas</th>
            <th>Tarif</th>
            <th>Kapasitas</th>
            <th>Hapus</th>
        </tr>
    </table>
    <button class="tambah-kelas-tiket">Tambah</button>
    <br>
    <button type="submit" id='submitUpdate'>Create</button>
    <a href="{% url 'event:daftar_event' %}">Cancel</a>
</form>
{% endblock content %}

{% block script %}
<script>
    
// Lokasi
const stateGedung = {
    dataGedung:[],
    dataKelasTiket:[],
}

$('input').change(e => {
    data[e.target.name] = e.target.value
})
fetch("{% url 'event:get_lokasi' id %}").then(r=>r.json()).then(d=>{
    stateGedung.dataGedung=d.data
    renderGedung(stateGedung.dataGedung)
})

function renderGedung(data) {
    $('.formContainerGedung').html('')
    $('.formContainerGedung').append(`<tr style="color:white">
            <th>Nama Gedung</th>
            <th>Kota</th>
            <th>Alamat</th>
            <th>Hapus</th>
        </tr>`)
    data.map((gedung, idx)=> {  
        const row = $('<tr></tr>')
        const nama_gedung_input = $(`<input type="text" name="nama_gedung" placeholder="Nama Gedung" required  value="">`)
        const kota_input = $(`<input type="text" name="kota" placeholder="Kota" required value="">`)
        const alamat_input = $(`<input type="text" name="alamat" placeholder="Alamat" required value="">`)
        nama_gedung_input.change(e=>{
            stateGedung.dataGedung[idx]['nama_gedung']=e.target.value
        })
        kota_input.change(e=>{
            stateGedung.dataGedung[idx]['kota']=e.target.value
        })
        alamat_input.change(e=>{
            stateGedung.dataGedung[idx]['alamat']=e.target.value
        })
        row.append($('<td></td>').append(nama_gedung_input))
        row.append($('<td></td>').append(kota_input))
        row.append($('<td></td>').append(alamat_input))
        row.append($('<td></td>').append('<a href="#">Hapus</a>'))
        $('.formContainerGedung').append(row)
        })
    }

$('.tambah-gedung').click((e)=>{
        e.preventDefault()
        stateGedung.dataGedung.push({
            nama_gedung:'',
            kota:'',
            alamat:''
        })
        renderGedung(stateGedung.dataGedung)
    })

// Kelas Tiket
fetch("{% url 'event:get_kelas_tiket' id %}").then(r=>r.json()).then(d=>{
    stateGedung.dataKelasTiket=d.data
    renderKelasTiket(stateGedung.dataKelasTiket)
})

function renderKelasTiket(data) {
    $('.formContainerKelasTiket').html('')
    $('.formContainerKelasTiket').append(`<tr style="color:white">
            <th>Nama Kelas</th>
            <th>Tarif</th>
            <th>Kapasitas</th>
            <th>Hapus</th>
        </tr>`)
    data.map((kelasTiket, idx)=> {  
        const row = $('<tr></tr>')
        const nama_kelas_input = $(`<input type="text" name="nama_kelas" placeholder="Nama Kelas" required  value="">`)
        const tarif_input = $(`<input type="number" name="tarif" placeholder="Tarif" required value=""">`)
        const kapasitas_input = $(`<input type="number" name="kapasitas" placeholder="Kapasitas" required value="">`)
        nama_kelas_input.change(e=>{
            stateGedung.dataKelasTiket[idx]['nama_kelas']=e.target.value
        })
        tarif_input.change(e=>{
            stateGedung.dataKelasTiket[idx]['tarif']=e.target.value
        })
        kapasitas_input.change(e=>{
            stateGedung.dataKelasTiket[idx]['kapasitas']=e.target.value
        })
        row.append($('<td></td>').append(nama_kelas_input))
        row.append($('<td></td>').append(tarif_input))
        row.append($('<td></td>').append(kapasitas_input))
        row.append($('<td></td>').append('<a href="#">Hapus</a>'))
        $('.formContainerKelasTiket').append(row)
        })
    }

$('input').change(e => {
    if (e.target.name !== 'dataGedung' && e.target.name !== 'dataKelasTiket') {
        data[e.target.name] = e.target.value
    }   
})

$('.tambah-kelas-tiket').click((e)=>{
        e.preventDefault()
        stateGedung.dataKelasTiket.push({
            nama_kelas:'',
            tarif:0,
            kapasitas:0
        })
        renderKelasTiket(stateGedung.dataKelasTiket)
    })

$('form').submit(e=>{
    e.preventDefault()
    fetch("{% url 'event:update_event' id %}", {
        method: "post",
        headers: {
            'X-CSRFToken': getCookie("csrftoken"),
            'Accept': 'application/json',
            'Content-Type': 'application/json'
        },

        //make sure to serialize your JSON body
        body: JSON.stringify({
            ...stateGedung,
            'dataKelasTiket':stateGedung.dataKelasTiket,
            'dataGedung':stateGedung.dataGedung
        })
    })
    .then( (response) => { 
    //do something awesome that makes the world a better place
});
})

function getCookie(c_name)
    {
        if (document.cookie.length > 0)
        {
            c_start = document.cookie.indexOf(c_name + "=");
            if (c_start != -1)
            {
                c_start = c_start + c_name.length + 1;
                c_end = document.cookie.indexOf(";", c_start);
                if (c_end == -1) c_end = document.cookie.length;
                return unescape(document.cookie.substring(c_start,c_end));
            }
        }
        return "";
    }
</script>
{% endblock script %}

event/templates/event/daftar_event.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Event{% endblock title %}

{% block css %} 
<link rel="stylesheet" href="{% static 'event/css/daftar_event.css' %}">
{% endblock css %}

{% block content %}
<h1 class="text-center">Event+ - Daftar Event</h1>
{% if role == 'Organizer' %}
{% endif %}
<form action="/" method="get">
  <input type="text" name="q" placeholder="Search Box">
  <button type="submit">Search</button>
</form>
<table class="table table-dark table-striped" >
    <tr>
      <th>Nama Tema</th>
      <th>Nama Event</th>
      <th>Organizer</th>
      <th>Lokasi</th>
      <th>Tanggal</th>
      <th>Jam</th>
      <th>Kapasitas</th>
      {% if role == 'Organizer' %}
      <th>Edit Event</th>
      <th>Delete Event</th>
      {% else %}
      <th>Pesan Tiket </th>
      {% endif %}
    </tr>
    {% for e in page %}
    <tr>
        <td>{{ e.nama_tema }}</td>
        <td>{{ e.nama }}</td>
        <td>{{ e.nama_organizer }}</td>
        <td>{{ e.nama_gedung }}</td>
        <td>{{ e.tanggal_mulai }} - {{ e.tanggal_selesai }}</td>
        {% if e.jam_mulai != None %}
          <td>{{ e.jam_mulai }} - {{ e.jam_selesai }}</td>
        {% else %}
          <td></td>
        {% endif %}
        <td>{{ e.kapasitas_total_tersedia }}</td>
        {% if role == 'Organizer' %}
          {% if email == e.email_organizer %}
            {% if time < e.tanggal_selesai %}
              <td><a href="{% url 'event:update_event' e.id_event%}">Edit</a></td>
              <td><a href="{% url 'event:delete_event' e.id_event %}">Delete</a></td>
            {% else %}
              <td></td>
              <td></td>
            {% endif %}
          {% else %}
            <td></td>
            <td></td>
          {% endif %}
        {% else %}
          <td>{% if e.kapasitas_total_tersedia == 0 or time < e.tanggal_selesai %}  {% else %} <a href="{% url 'pesanan:pesan_tiket' %}">Pesan Tiket</a> {% endif %}</td>
        {% endif %}
    </tr>
    {% endfor %}
</table>

{% if page.has_other_pages %}
<ul class="pagination">
  {% if page.has_previous %}
    <li class ="page-link"><a href="?page={{ page.previous_page_number }}">&laquo;</a></li>
  {% else %}
    <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
  {% endif %}

  {% for i in page.paginator.page_range %}
    {% if page.number == i %}
      <li class="page-item active">
        <div class="page-link">
          Page <span>{{ i }}<span class="sr-only"></span></span>
        </div> 
      </li>
    {% else %}
      <li class="page-link"><a href="?page={{ i }}">{{ i }}</a></li>
    {% endif %}
  {% endfor %}
  {% if page.has_next %}
    <li class="page-link"><a href="?page={{ user.next_page_number }}">&raquo;</a></li>
  {% else %}
    <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
  {% endif %}
</ul>
{% endif %}
{% endblock content %}

event/templates/event/delete.html
{% extends 'base.html' %}

{% block title %}Create Event{% endblock title %}

{% block content %}
<h1 class="text-center">Event+ - Hapus Event</h1>
<p>Apakah anda yakin untuk menghapus event ini?</p>

<a href="{% url 'event:confirm_delete' id %}">Ya</a>
<a href="{% url 'event:daftar_event' %}">Tidak</a>
{% endblock content %}

event/templates/event/my_event.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Event{% endblock title %}

{% block content %}
<h1 class="text-center">Event+ - Daftar Event Saya</h1>
<table class="table table-dark table-striped">
    <tr>
      <th>Nama Tema</th>
      <th>Nama Event</th>
      <th>Lokasi</th>
      <th>Tanggal</th>
      <th>Jam</th>
      <th>Kapasitas</th>
      <th>Edit Event</th>
      <th>Delete Event</th>
    </tr>
    {% for e in event %}
    <tr>
        <td>{{ e.nama_tema }}</td>
        <td>{{ e.nama }}</td>
        <td>{{ e.nama_gedung }}</td>
        <td>{{ e.tanggal_mulai }} - {{ e.tanggal_selesai }}</td>
        {% if e.jam_mulai != None %}
        <td>{{ e.jam_mulai }} - {{ e.jam_selesai }}</td>
        {% else %}
        <td></td>
        {% endif %}
        <td>{{ e.kapasitas_total_tersedia }}</td>
        {% if time < e.tanggal_selesai %}
        <td><a href="{% url 'event:update_event' e.id_event%}">Edit</a></td>
        <td><a href="{% url 'event:delete_event' e.id_event %}">Delete</a></td>
        {% else %}
        <td></td>
        <td></td>
        {% endif %}
    </tr>
    {% endfor %}
</table>
{% endblock content %}

event/templates/event/update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %} 

{% block title %}Update Event{% endblock title %}

{% block content %}
<h1 class="text-center">Update Event</h1>
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <p>Lokasi</p>
    <table class="table table-light table-striped formContainerGedung">
        <tr>
            <th>Nama Gedung</th>
            <th>Kota</th>
            <th>Alamat</th>
            <th>Hapus</th>
        </tr>
    </table>
    <button class="tambah-gedung">Tambah</button>
    
    <p>Kelas Tiket</p>
    <table class="table table-light table-striped formContainerKelasTiket">
        <tr>
            <th>Nama Kelas</th>
            <th>Tarif</th>
            <th>Kapasitas</th>
            <th>Hapus</th>
        </tr>
    </table>
    <button class="tambah-kelas-tiket">Tambah</button>
    <br>
    <button type="submit" id='submitUpdate'>Update</button>
    <a href="{% url 'event:daftar_event' %}">Cancel</a>
</form>
{% endblock content %}

{% block script %}
<script>
    
// Lokasi
const stateGedung = {
    nama: $("input[name='nama']").val(),
    desc: $("input[name='desc']").val(),
    tema: $("input[name='tema']").val(),
    tema: $("input[name='tema']").val(),
    dataGedung:[],
    dataKelasTiket:[],
}
console.log($("input[name='tema']").val())

$('input').change(e => {
    data[e.target.name] = e.target.value
})
fetch("{% url 'event:get_lokasi' id %}").then(r=>r.json()).then(d=>{
    stateGedung.dataGedung=d.data
    renderGedung(stateGedung.dataGedung)
})

function renderGedung(data) {
    $('.formContainerGedung').html('')
    $('.formContainerGedung').append(`<tr style="color:white">
            <th>Nama Gedung</th>
            <th>Kota</th>
            <th>Alamat</th>
            <th>Hapus</th>
        </tr>`)
    data.map((gedung, idx)=> {  
        const row = $('<tr></tr>')
        const nama_gedung_input = $(`<input type="text" name="nama_gedung" placeholder="Nama Gedung" required  value="${gedung.nama_gedung}">`)
        const kota_input = $(`<input type="text" name="kota" placeholder="Kota" required value="${gedung.kota}">`)
        const alamat_input = $(`<input type="text" name="alamat" placeholder="Alamat" required value="${gedung.alamat}">`)
        nama_gedung_input.change(e=>{
            stateGedung.dataGedung[idx]['nama_gedung']=e.target.value
        })
        kota_input.change(e=>{
            stateGedung.dataGedung[idx]['kota']=e.target.value
        })
        alamat_input.change(e=>{
            stateGedung.dataGedung[idx]['alamat']=e.target.value
        })
        row.append($('<td></td>').append(nama_gedung_input))
        row.append($('<td></td>').append(kota_input))
        row.append($('<td></td>').append(alamat_input))
        row.append($('<td></td>').append('<a href="#">Hapus</a>'))
        $('.formContainerGedung').append(row)
        })
    }

$('.tambah-gedung').click((e)=>{
        e.preventDefault()
        stateGedung.dataGedung.push({
            nama_gedung:'',
            kota:'',
            alamat:''
        })
        renderGedung(stateGedung.dataGedung)
    })

// Kelas Tiket
fetch("{% url 'event:get_kelas_tiket' id %}").then(r=>r.json()).then(d=>{
    stateGedung.dataKelasTiket=d.data
    renderKelasTiket(stateGedung.dataKelasTiket)
})

function renderKelasTiket(data) {
    $('.formContainerKelasTiket').html('')
    $('.formContainerKelasTiket').append(`<tr style="color:white">
            <th>Nama Kelas</th>
            <th>Tarif</th>
            <th>Kapasitas</th>
            <th>Hapus</th>
        </tr>`)
    data.map((kelasTiket, idx)=> {  
        const row = $('<tr></tr>')
        const nama_kelas_input = $(`<input type="text" name="nama_kelas" placeholder="Nama Kelas" required  value="${kelasTiket.nama_kelas}">`)
        const tarif_input = $(`<input type="number" name="tarif" placeholder="Tarif" required value="${kelasTiket.tarif}">`)
        const kapasitas_input = $(`<input type="number" name="kapasitas" placeholder="Kapasitas" required value="${kelasTiket.kapasitas}">`)
        nama_kelas_input.change(e=>{
            stateGedung.dataKelasTiket[idx]['nama_kelas']=e.target.value
        })
        tarif_input.change(e=>{
            stateGedung.dataKelasTiket[idx]['tarif']=e.target.value
        })
        kapasitas_input.change(e=>{
            stateGedung.dataKelasTiket[idx]['kapasitas']=e.target.value
        })
        row.append($('<td></td>').append(nama_kelas_input))
        row.append($('<td></td>').append(tarif_input))
        row.append($('<td></td>').append(kapasitas_input))
        row.append($('<td></td>').append('<a href="#">Hapus</a>'))
        $('.formContainerKelasTiket').append(row)
        })
    }

$('input').change(e => {
    if (e.target.name !== 'dataGedung' && e.target.name !== 'dataKelasTiket') {
        data[e.target.name] = e.target.value
    }   
})

$('.tambah-kelas-tiket').click((e)=>{
        e.preventDefault()
        stateGedung.dataKelasTiket.push({
            nama_kelas:'',
            tarif:0,
            kapasitas:0
        })
        renderKelasTiket(stateGedung.dataKelasTiket)
    })

$('form').submit(e=>{
    e.preventDefault()
    fetch("{% url 'event:update_event' id %}", {
        method: "post",
        headers: {
            'X-CSRFToken': getCookie("csrftoken"),
            'Accept': 'application/json',
            'Content-Type': 'application/json'
        },

        //make sure to serialize your JSON body
        body: JSON.stringify({
            ...stateGedung,
            'dataKelasTiket':stateGedung.dataKelasTiket,
            'dataGedung':stateGedung.dataGedung
        })
    })
    .then( (response) => { 
    //do something awesome that makes the world a better place
});
})

function getCookie(c_name)
    {
        if (document.cookie.length > 0)
        {
            c_start = document.cookie.indexOf(c_name + "=");
            if (c_start != -1)
            {
                c_start = c_start + c_name.length + 1;
                c_end = document.cookie.indexOf(";", c_start);
                if (c_end == -1) c_end = document.cookie.length;
                return unescape(document.cookie.substring(c_start,c_end));
            }
        }
        return "";
    }
</script>
{% endblock script %}