blue/urls.py
from django.urls import path
from .views import *

app_name = 'blue'

urlpatterns = [
    path('profil', profil, name='profil'),
    path('editProfilPengunjung', editProfilPengunjung, name='editProfilPengunjung'),
    path('editProfilIndividu', editProfilIndividu, name='editProfilIndividu'),
    path('editProfilPerusahaan', editProfilPerusahaan, name='editProfilPerusahaan'),
    path('dompetDigital', dompetDigital, name='dompetDigital'),
    path('tambahSaldo', tambahSaldo, name='tambahSaldo'),
]

eventplus/urls.py
from django.contrib import admin
from django.urls import path, include
from user.views import *
from landingpage.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('registerpengunjung/', registerPengunjung, name='register_pengunjung'),
    path('registerorganizer/', registerOrganizer, name='register_organizer'),
    path('transaksi/', include('transaksi.urls')),
    path('testimoni/', include('testimoni.urls')),
    path('', include('event.urls')),
    path('pesanan/', include('pesanan.urls')),
    path('blue/', include('blue.urls')),
]

pesanan/urls.py
from django.urls import path
from . import views

app_name = 'pesanan'

urlpatterns = [
	path('', views.pesan_tiket_view, name='pesan_tiket'),
	path('add/<str:pk>/', views.add_daftar_tiket_view, name='add_daftar_tiket'),
	path('delete/<str:pk>/', views.delete_daftar_tiket_view, name='delete_daftar_tiket'),
	path('buat/<str:pk>/', views.buat_transaksi_view, name='buat_transaksi'),
	path('cancel/<str:pk>/', views.cancel_pesan_tiket_view, name='cancel_pesan_tiket'),
	path('transaksi_saya/', views.transaksi_saya_view, name='transaksi_saya'),
	path('transaksi_saya/edit/<str:pk>/', views.edit_transaksi_view, name='edit_transaksi'),
	path('transaksi_saya/delete/<str:pk>/', views.delete_transaksi_view, name='delete_transaksi'),
]

transaksi/urls.py
from django.urls import path
from . import views

app_name = 'transaksi'

urlpatterns = [
    path('<str:pk>', views.transaksi, name='transaksi'),
    path('konfirmasi-transaksi/<str:pk>', views.konfirmasiTransaksi, name='konfirmasiTransaksi'),
]

pesanan/models.py
from django.db import models

# Create your models here.

pesanan/views.py
from django.shortcuts import render, redirect
from datetime import datetime
from collections import namedtuple
from .connection import *
import random
import string

# Create your views here.
def pesan_tiket_view(request):
	if not request.session.get('user_email'):
		email = 'rison0@dagondesign.com'
	else:
		email = request.session.get('user_email')

	event_id = 'EVENT00'

	# Mengecek apakah ada Transaksi yang belum dipesan untuk event tersebut
	cekTransaksi = cekTransaksiQuery(email, event_id)

	# Jika tidak ditemukan Transaksi, buat Shared_Profit & Transaksi baru
	if list(cekTransaksi):
		waktu = cekTransaksi[0][1]
		tanggal = cekTransaksi[0][2]

	# Jika ditemukan Transaksi, ambil waktu dan tanggal
	else:
		waktu = datetime.now().strftime("%H:%M")
		tanggal = datetime.now().strftime("%Y-%m-%d")

		sp_id = generate_id()
		createNewSharedProfitQuery(sp_id)
		createNewTransaksiQuery(email, waktu, tanggal, sp_id)

	eventDetails = getEventDetailsQuery(event_id)
	allKelasTiket = getAllKelasTiketQuery(event_id)
	myDaftarTiket = getMyDaftarTiketQuery(email, waktu, tanggal, event_id)

	context = {
		'event': eventDetails[0],
		'kelasTiket': allKelasTiket,
		'daftarTiket': myDaftarTiket,
		'transaksi': cekTransaksi[0],
	}

	return render(request, 'pesan_tiket.html', context)

def add_daftar_tiket_view(request, pk):
	if not request.session.get('user_email'):
		email = 'rison0@dagondesign.com'
	else:
		email = request.session.get('user_email')

	event_id = 'EVENT00'
	email_pemilik = generate_email()

	daftar = pk.split(";")
	waktu = daftar[0]
	tanggal = daftar[1]
	nama_kelas_tiket = daftar[2]

	addDaftarTiketQuery(email, email_pemilik, waktu, tanggal, event_id, nama_kelas_tiket)
	return redirect('pesanan:pesan_tiket')

def delete_daftar_tiket_view(request, pk):
	if not request.session.get('user_email'):
		email = 'rison0@dagondesign.com'
	else:
		email = request.session.get('user_email')

	event_id = 'EVENT00'

	daftar = pk.split(";")
	email_pemilik = daftar[0]
	waktu = daftar[1]
	tanggal = daftar[2]
	nama_kelas_tiket = daftar[3]

	deleteDaftarTiketQuery(email, email_pemilik, waktu, tanggal, event_id, nama_kelas_tiket)
	return redirect('pesanan:pesan_tiket')

def buat_transaksi_view(request, pk):
	if not request.session.get('user_email'):
		email = 'rison0@dagondesign.com'
	else:
		email = request.session.get('user_email')

	daftar = pk.split(";")
	waktu = daftar[0]
	tanggal = daftar[1]

	buatTransaksiQuery(email, waktu, tanggal)
	return redirect('event:daftar_event')

def cancel_pesan_tiket_view(request, pk):
	if not request.session.get('user_email'):
		email = 'rison0@dagondesign.com'
	else:
		email = request.session.get('user_email')

	daftar = pk.split(";")
	waktu = daftar[0]
	tanggal = daftar[1]

	deleteTransaksiQuery(email, waktu, tanggal)
	return redirect('event:daftar_event')

def transaksi_saya_view(request):
	if not request.session.get('user_email'):
		email = 'rison0@dagondesign.com'
	else:
		email = request.session.get('user_email')

	allTransaksi = getAllTransaksiQuery(email)

	context = {
		'transaksi': allTransaksi,
	}
	return render(request, 'transaksi_saya.html', context)

def edit_transaksi_view(request, pk):
	if not request.session.get('user_email'):
		email = 'rison0@dagondesign.com'
	else:
		email = request.session.get('user_email')

	daftar = pk.split(";")
	waktu = daftar[0]
	tanggal = daftar[1]

	event = getEventQuery(email, waktu, tanggal)
	event_id = event[0][0]

	eventDetails = getEventDetailsQuery(event_id)
	allKelasTiket = getAllKelasTiketQuery(event_id)
	myDaftarTiket = getMyDaftarTiketQuery(email, waktu, tanggal, event_id)

	context = {
		'event': eventDetails[0],
		'kelasTiket': allKelasTiket,
		'daftarTiket': myDaftarTiket,
		'waktu': waktu,
		'tanggal': tanggal,
	}

	return render(request, 'update_tiket.html', context)

def delete_transaksi_view(request, pk):
	if not request.session.get('user_email'):
		email = 'rison0@dagondesign.com'
	else:
		email = request.session.get('user_email')

	daftar = pk.split(";")
	waktu = daftar[0]
	tanggal = daftar[1]

	deleteTransaksiQuery(email, waktu, tanggal)
	return redirect('pesanan:transaksi_saya')

def generate_id():
	number = random.randint(1, 9999)
	return 'SP{}{}'.format(datetime.now().strftime('%Y%m%d%H%M%S'), number)

def generate_email():
	email = "".join(random.choice(string.ascii_letters) for x in range(10))
	return (email + "@gmail.com")

pesanan/templates/pesan_tiket.html
{% extends 'base.html' %}
{% load static %}
{% load pesanan_extras %}

{% block title %}Pesan Tiket{% endblock title %}

{% block css %}
<!-- Bootstrap CDN CSS -->
<link rel="stylesheet"
href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
crossorigin="anonymous">

<!-- Quicksand Font Link -->
<link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">
{% endblock css %}

{% block content %}


<h1 style="font-family: Quicksand; font-weight: bold; font-size: 40px; margin-top:40px; padding-left:5%; padding-right:5%; text-align:center;">PESAN TIKET</h1> </br>


<h3 style="font-family: Quicksand; font-weight: bold; font-size: 18px; padding-left:5%; padding-right:5%;">
> Tema Event: [ {{ event.nama_tema }} ]</h3>

<h3 style="font-family: Quicksand; font-weight: bold; font-size: 18px; padding-left:5%; padding-right:5%;">
> Nama Event: [ {{ event.nama }} ]</h3>

<h3 style="font-family: Quicksand; font-weight: bold; font-size: 18px; padding-left:5%; padding-right:5%;">
> Deskripsi Event: [ {{ event.deskripsi }} ]</h3>

<h3 style="font-family: Quicksand; font-weight: bold; font-size: 18px; padding-left:5%; padding-right:5%;">
> Tanggal: [ {{ event.tanggal_mulai }} ] - [ {{ event.tanggal_selesai }} ]</h3>

<h3 style="font-family: Quicksand; font-weight: bold; font-size: 18px; padding-left:5%; padding-right:5%;">
> Lokasi Event: [ {{ event.nama_gedung }}, {{ event.kota }}, {{ event.alamat }} ]</h3>

<h3 style="font-family: Quicksand; font-weight: bold; font-size: 18px; padding-left:5%; padding-right:5%;">
> Tipe Event: [ {{ event.nama_tipe }} ]</h3>


{% for kelas in kelasTiket %}

<h2 style="font-family: Quicksand; font-weight: bold; font-size: 25px; margin-top:30px; padding-left:2%; padding-right:2%;text-align:center;">
	[Nama Kelas Tiket: '{{ kelas.nama_kelas }}'] – [Tarif Kelas Tiket: '{{ kelas.tarif }}'] –
	[Kapasitas Kelas Tiket: '{{ kelas.kapasitas }}'] – [Kapasitas Kelas Tersedia Tiket: '{{ kelas.kapasitas_tersedia }}']</h2>

<!-- Bootstrap Card Group -->
<div class="container" style="margin-top:40px; margin-bottom:40px; padding-right:2%; padding-left:2%;">

	<!-- Card Containing UserCreationForm -->
	<div class="card" style="box-shadow: 0px 4px 14px rgba(0, 0, 0, 0.25);">

		<!-- Card Body -->
		<div class="container" style="margin-top:40px; margin-bottom:40px;">


			<table style="width:100%">
				<tr>
					<th style="text-align:center;">Nama Pemesan</th>
					<th style="text-align:center;">Email Pemesan</th>
					<th style="text-align:center;">Hapus Pemesanan</th>
				</tr>

				{% for daftar in daftarTiket %}
				{% if daftar.nama_kelas == kelas.nama_kelas %}
    			<tr>
        			<td style="text-align:center;">[{{ daftar.nama_pemilik_tiket }}]</td>
        			<td style="text-align:center;">[{{ daftar.email_pemilik_tiket }}]</td>
        			<td style="text-align:center;"><a href="{% url 'pesanan:delete_daftar_tiket' daftar.email_pemilik_tiket|addstr:';'|addstr:daftar.waktu_transaksi|addstr:';'|addstr:daftar.tanggal_transaksi|addstr:';'|addstr:daftar.nama_kelas %}">
        			[Hapus Row]</a></td>
    			</tr>
    			{% endif %}
    			{% endfor %}

			</table> </br>

			<a style="padding-left:5%;" href="{% url 'pesanan:add_daftar_tiket' transaksi.waktu|addstr:';'|addstr:transaksi.tanggal|addstr:';'|addstr:kelas.nama_kelas %}">
			[Tambah Row]</a> </br>

		</div>
	</div>
</div>

{% endfor %}


<div style="margin-bottom:40px; padding-left:5%; padding-right:5%;">
	<a style="padding-right:5%;" href="{% url 'pesanan:buat_transaksi' transaksi.waktu|addstr:';'|addstr:transaksi.tanggal %}">[Buat Transaksi]</a> 
	<a style="padding-left:5%;" href="{% url 'pesanan:cancel_pesan_tiket' transaksi.waktu|addstr:';'|addstr:transaksi.tanggal %}">[Cancel]</a>
</div>

{% endblock content %}

{% block script %}

<!-- Bootstrap CDN JS -->
<!-- jQuery library -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
crossorigin="anonymous"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" 
integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" 
crossorigin="anonymous"></script>

<!-- Bootstrap JavaScript -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" 
integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" 
crossorigin="anonymous"></script>

{% endblock script %}

pesanan/templates/transaksi_saya.html
{% extends 'base.html' %}
{% load static %}
{% load pesanan_extras %}

{% block title %}Transaksi Saya{% endblock title %}

{% block css %}
<!-- Bootstrap CDN CSS -->
<link rel="stylesheet"
href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
crossorigin="anonymous">

<!-- Quicksand Font Link -->
<link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">
{% endblock css %}

{% block content %}

<h1 style="font-family: Quicksand; font-weight: bold; font-size: 40px; margin-top:40px; padding-left:5%; padding-right:5%; text-align:center;">TRANSAKSI SAYA</h1> </br>

<!-- Bootstrap Card Group -->
<div class="container" style="margin-top:40px; margin-bottom:40px; padding-right:2%; padding-left:2%;">

	<!-- Card Containing UserCreationForm -->
	<div class="card" style="box-shadow: 0px 4px 14px rgba(0, 0, 0, 0.25);">

		<!-- Card Body -->
		<div class="container" style="margin-top:40px; margin-bottom:40px;">


			<table style="width:100%">
				<tr>
					<th style="text-align:center;">Tanggal Transaksi</th>
					<th style="text-align:center;">Waktu Transaksi</th>
					<th style="text-align:center;">Status Transaksi</th>
					<th style="text-align:center;">Total Bayar</th>
					<th style="text-align:center;">[Edit Transaksi]</th>
					<th style="text-align:center;">[Delete Transaksi]</th>
				</tr>

                {% for t in transaksi %}

    			<tr>
        			<td style="text-align:center;">{{ t.tanggal }}</td>
        			<td style="text-align:center;">{{ t.waktu }}</td>

					{% if t.status == 'Incomplete' %}
                    <td style="text-align:center;"><a href="{% url 'transaksi:transaksi' t.waktu|addstr:';'|addstr:t.tanggal %}">{{ t.status }}</a></td>

                    {% else %}
        			<td style="text-align:center;">{{ t.status }}</td>

                    {% endif %}

        			<td style="text-align:center;">{{ t.total_bayar }}</td>
        			<td style="text-align:center;"><a href="{% url 'pesanan:edit_transaksi' t.waktu|addstr:';'|addstr:t.tanggal %}">[Edit]</a></td>
        			<td style="text-align:center;">
                        <a href="{% url 'pesanan:delete_transaksi' t.waktu|addstr:';'|addstr:t.tanggal %}">
                        [Delete]</a>
                    </td>
    			</tr>

                {% endfor %}

    			<tr>
        			<td style="text-align:center;">dst</td>
        			<td style="text-align:center;">dst</td>
        			<td style="text-align:center;">dst</td>
        			<td style="text-align:center;">dst</td>
        			<td style="text-align:center;">dst</td>
        			<td style="text-align:center;">dst</td>
    			</tr>
			</table> </br>

		</div>
	</div>
</div>

{% endblock content %}

{% block script %}

<!-- Bootstrap CDN JS -->
<!-- jQuery library -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
crossorigin="anonymous"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" 
integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" 
crossorigin="anonymous"></script>

<!-- Bootstrap JavaScript -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" 
integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" 
crossorigin="anonymous"></script>

{% endblock script %}

pesanan/templates/update_tiket.html
{% extends 'base.html' %}
{% load static %}
{% load pesanan_extras %}

{% block title %}Update Tiket Event{% endblock title %}

{% block css %}
<!-- Bootstrap CDN CSS -->
<link rel="stylesheet"
href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
crossorigin="anonymous">

<!-- Quicksand Font Link -->
<link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">
{% endblock css %}

{% block content %}


<h1 style="font-family: Quicksand; font-weight: bold; font-size: 40px; margin-top:40px; padding-left:5%; padding-right:5%; text-align:center;">UPDATE TIKET EVENT</h1> </br>


<h3 style="font-family: Quicksand; font-weight: bold; font-size: 18px; padding-left:5%; padding-right:5%;">
> Tema Event: [ {{ event.nama_tema }} ]</h3>

<h3 style="font-family: Quicksand; font-weight: bold; font-size: 18px; padding-left:5%; padding-right:5%;">
> Nama Event: [ {{ event.nama }} ]</h3>

<h3 style="font-family: Quicksand; font-weight: bold; font-size: 18px; padding-left:5%; padding-right:5%;">
> Deskripsi Event: [ {{ event.deskripsi }} ]</h3>

<h3 style="font-family: Quicksand; font-weight: bold; font-size: 18px; padding-left:5%; padding-right:5%;">
> Tanggal: [ {{ event.tanggal_mulai }} ] - [ {{ event.tanggal_selesai }} ]</h3>

<h3 style="font-family: Quicksand; font-weight: bold; font-size: 18px; padding-left:5%; padding-right:5%;">
> Lokasi Event: [ {{ event.nama_gedung }}, {{ event.kota }}, {{ event.alamat }} ]</h3>

<h3 style="font-family: Quicksand; font-weight: bold; font-size: 18px; padding-left:5%; padding-right:5%;">
> Tipe Event: [ {{ event.nama_tipe }} ]</h3>


{% for kelas in kelasTiket %}

<h2 style="font-family: Quicksand; font-weight: bold; font-size: 25px; margin-top:30px; padding-left:2%; padding-right:2%;text-align:center;">
	[Nama Kelas Tiket: '{{ kelas.nama_kelas }}'] – [Tarif Kelas Tiket: '{{ kelas.tarif }}'] –
	[Kapasitas Kelas Tiket: '{{ kelas.kapasitas }}'] – [Kapasitas Kelas Tersedia Tiket: '{{ kelas.kapasitas_tersedia }}']</h2>

<!-- Bootstrap Card Group -->
<div class="container" style="margin-top:40px; margin-bottom:40px; padding-right:2%; padding-left:2%;">

	<!-- Card Containing UserCreationForm -->
	<div class="card" style="box-shadow: 0px 4px 14px rgba(0, 0, 0, 0.25);">

		<!-- Card Body -->
		<div class="container" style="margin-top:40px; margin-bottom:40px;">


			<table style="width:100%">
				<tr>
					<th style="text-align:center;">Nama Pemesan</th>
					<th style="text-align:center;">Email Pemesan</th>
					<th style="text-align:center;">Hapus Pemesanan</th>
				</tr>

				{% for daftar in daftarTiket %}
				{% if daftar.nama_kelas == kelas.nama_kelas %}
    			<tr>
        			<td style="text-align:center;">[{{ daftar.nama_pemilik_tiket }}]</td>
        			<td style="text-align:center;">[{{ daftar.email_pemilik_tiket }}]</td>
        			<td style="text-align:center;"><a href="{% url 'pesanan:delete_daftar_tiket' daftar.email_pemilik_tiket|addstr:';'|addstr:daftar.waktu_transaksi|addstr:';'|addstr:daftar.tanggal_transaksi|addstr:';'|addstr:daftar.nama_kelas %}">
        			[Hapus Row]</a></td>
    			</tr>
    			{% endif %}
    			{% endfor %}

			</table> </br>

			<a style="padding-left:5%;" href="{% url 'pesanan:add_daftar_tiket' waktu|addstr:';'|addstr:tanggal|addstr:';'|addstr:kelas.nama_kelas %}">
			[Tambah Row]</a> </br>

		</div>
	</div>
</div>

{% endfor %}


<div style="margin-bottom:40px; padding-left:5%; padding-right:5%;">
	<a style="padding-right:5%;" href="{% url 'pesanan:buat_transaksi' waktu|addstr:';'|addstr:tanggal %}">[Update Transaksi]</a> 
	<a style="padding-left:5%;" href="{% url 'pesanan:cancel_pesan_tiket' waktu|addstr:';'|addstr:tanggal %}">[Cancel]</a>
</div>

{% endblock content %}

{% block script %}

<!-- Bootstrap CDN JS -->
<!-- jQuery library -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
crossorigin="anonymous"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" 
integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" 
crossorigin="anonymous"></script>

<!-- Bootstrap JavaScript -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" 
integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" 
crossorigin="anonymous"></script>

{% endblock script %}