blue/urls.py
from django.urls import path
from .views import *

app_name = 'blue'

urlpatterns = [
    path('profil', profil, name='profil'),
    path('editProfilPengunjung', editProfilPengunjung, name='editProfilPengunjung'),
    path('editProfilIndividu', editProfilIndividu, name='editProfilIndividu'),
    path('editProfilPerusahaan', editProfilPerusahaan, name='editProfilPerusahaan'),
    path('dompetDigital', dompetDigital, name='dompetDigital'),
    path('tambahSaldo', tambahSaldo, name='tambahSaldo'),
]

event/urls.py
from django.urls import path
from .views import *

app_name = 'event'

urlpatterns = [
    path('', daftar_event, name='daftar_event'),
    path('my_event', my_event, name='my_event'),
    path('create/', create, name='create_event'),
    path('update/<str:id>/', update, name='update_event'),
    path('delete/<str:id>/', delete, name='delete_event'),
    path('deleteconfirm/<str:id>/',confirmDelete, name='confirm_delete'),
    path('getLokasi/<str:id>/', getLokasi, name='get_lokasi'),
    path('getKelasTiket/<str:id>/', getKelasTiket, name='get_kelas_tiket')
]

eventplus/urls.py
from django.contrib import admin
from django.urls import path, include
from user.views import *
from landingpage.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('registerpengunjung/', registerPengunjung, name='register_pengunjung'),
    path('registerorganizer/', registerOrganizer, name='register_organizer'),
    path('transaksi/', include('transaksi.urls')),
    path('testimoni/', include('testimoni.urls')),
    path('', include('event.urls')),
    path('pesanan/', include('pesanan.urls')),
    path('blue/', include('blue.urls')),
]

pesanan/urls.py
from django.urls import path
from . import views

app_name = 'pesanan'

urlpatterns = [
	path('', views.pesan_tiket_view, name='pesan_tiket'),
	path('add/<str:pk>/', views.add_daftar_tiket_view, name='add_daftar_tiket'),
	path('delete/<str:pk>/', views.delete_daftar_tiket_view, name='delete_daftar_tiket'),
	path('buat/<str:pk>/', views.buat_transaksi_view, name='buat_transaksi'),
	path('cancel/<str:pk>/', views.cancel_pesan_tiket_view, name='cancel_pesan_tiket'),
	path('transaksi_saya/', views.transaksi_saya_view, name='transaksi_saya'),
	path('transaksi_saya/edit/<str:pk>/', views.edit_transaksi_view, name='edit_transaksi'),
	path('transaksi_saya/delete/<str:pk>/', views.delete_transaksi_view, name='delete_transaksi'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Title here{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">  
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block css %}{% endblock css %}
</head>
<body>
    <nav class="navbar navbar-dark bg-dark" style="margin-bottom: 75px;">
    <a class="navbar-brand" href="{% url 'event:daftar_event' %}">Event+</a>
    <div class="dropdown">
        <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="margin-left:80px; background-color: transparent; box-shadow: 0 0 0; color:white;">Menu</button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="{% url 'event:daftar_event' %}">Daftar Event</a>
            {% if auth %}
                {% if role == 'Organizer' %}
                    <a class="dropdown-item" href="{% url 'event:my_event' %}">Event Saya</a>
                    <a class="dropdown-item" href="{% url 'event:create_event' %}">Buat Event</a>
                {% else %}
                    <a class="dropdown-item" href="{% url 'pesanan:transaksi_saya' %}">Transaksi</a>
                {% endif %}
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'blue:profil' %}">Profile</a>
                    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
            {% else %}
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'login' %}">Log In</a>
                <a class="dropdown-item" href="{% url 'register' %}">Register</a>
            {% endif %}
        </div>
    </nav>
    <div class="container">
        {% block content %}{% endblock content %}
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    {% block script %}{% endblock script %}
</body>
</html>