blue/urls.py
from django.urls import path
from .views import *

app_name = 'blue'

urlpatterns = [
    path('profil', profil, name='profil'),
    path('editProfilPengunjung', editProfilPengunjung, name='editProfilPengunjung'),
    path('editProfilIndividu', editProfilIndividu, name='editProfilIndividu'),
    path('editProfilPerusahaan', editProfilPerusahaan, name='editProfilPerusahaan'),
    path('dompetDigital', dompetDigital, name='dompetDigital'),
    path('tambahSaldo', tambahSaldo, name='tambahSaldo'),
]

eventplus/urls.py
from django.contrib import admin
from django.urls import path, include
from user.views import *
from landingpage.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('registerpengunjung/', registerPengunjung, name='register_pengunjung'),
    path('registerorganizer/', registerOrganizer, name='register_organizer'),
    path('transaksi/', include('transaksi.urls')),
    path('testimoni/', include('testimoni.urls')),
    path('', include('event.urls')),
    path('pesanan/', include('pesanan.urls')),
    path('blue/', include('blue.urls')),
]

blue/models.py
from django.db import models

# Create your models here.

blue/views.py
from django.shortcuts import render, redirect
from django.db import InternalError, IntegrityError
from .connection import *

# Create your views here.

def profil(request):
    if not request.session.get('user_email'):
        return redirect('/')

    email = request.session['user_email']
    passw = getUser(email)

    profile = getCustomer(email)
    if (profile != None):
        context = {
            'profile': profile,
            'passw': passw
        }
        return render(request, 'blue/profilPengunjung.html', context)

    organizer = getOrganizer(email)

    profile = getIndividual(email)
    if (profile != None):
        context = {
            'profile': profile,
            'passw': passw,
            'organizer': organizer
        }
        return render(request, 'blue/profilIndividu.html', context)

    profile = getCompany(email)
    if (profile != None):
        context = {
            'profile': profile,
            'passw': passw,
            'organizer': organizer
        }
        return render(request, 'blue/profilPerusahaan.html', context)

def editProfilPengunjung(request):
    return render(request, 'blue/editProfilPengunjung.html')

def editProfilIndividu(request):
    return render(request, 'blue/editProfilIndividu.html')

def editProfilPerusahaan(request):
    return render(request, 'blue/editProfilPerusahaan.html')

def dompetDigital(request):
    context = {
        'wallet': getDigitalWallet
    }
    return render(request, 'blue/dompetDigital.html', context)

def tambahSaldo(request):
    return render(request, 'blue/tambahSaldo.html')

blue/templates/blue/dompetDigital.html
{% extends 'base.html' %}

{% block title %}Saldo Dompet{% endblock title %}



{% block content %}
<center>
    <h1>Dompet Digital</h1>
    <table style="width:50%">
        <tr>
            <th>Nama</th>
            <td>{{ wallet.nama }}</td>
        </tr>
        <tr>
            <th>Saldo</th>
            <td>{{ wallet.saldo }}</td>
        </tr>
        <tr>
            <th>Nomor Akun</th>
            <td>{{ wallet.no_akun }}</td>
        </tr>
        <tr>
            <th>Email Pengunjung</th>
            <td>{{ wallet.email_pengunjung }}</td>
        </tr>
        <tr>
            <th></th>
            <td></td>
        </tr>
        <tr>
            <th></th>
            <td></td>
        </tr>
        <tr>
            <th></th>
            <td><button href="{% url 'blue:tambahSaldo'}">Tambah Saldo</button></td>
        </tr>
    </table>
</center>

{% endblock content %}

blue/templates/blue/editProfilIndividu.html
{% extends 'base.html' %}

{% block title %}Edit Profil{% endblock title %}



{% block content %}
<center>
    <h1>Edit Profile</h1>
    <form action="/action_page.php">
        <label for="fname">Email:</label><br>
        <input type="text"><br>
        <label for="fname">Password:</label><br>
        <input type="text"><br>
        <label for="fname">NPWP:</label><br>
        <input type="text"><br>
        <label for="lname">Nomor KTP:</label><br>
        <input type="text"><br>
        <label for="fname">Nama Depan:</label><br>
        <input type="text"><br>
        <label for="fname">Nama Belakang:</label><br>
        <input type="text"><br><br>
        <input type="submit" value="Submit" href="{% url 'blue:ProfilIndividu'}">
    </form>
</center>
{% endblock content %}

blue/templates/blue/editProfilPengunjung.html
{% extends 'base.html' %}

{% block title %}Edit Profil{% endblock title %}



{% block content %}
<center>
    <h1>Edit Profile</h1>
    <form action="/action_page.php">
        <label for="fname">Email:</label><br>
        <input type="text"><br>
        <label for="fname">Password:</label><br>
        <input type="text"><br>
        <label for="fname">Nama Depan:</label><br>
        <input type="text"><br>
        <label for="fname">Nama Belakang:</label><br>
        <input type="text"><br>
        <input type="submit" value="Submit" href="{% url 'blue:ProfilPengunjung'}">
    </form>
</center>
{% endblock content %}

blue/templates/blue/editProfilPerusahaan.html
{% extends 'base.html' %}

{% block title %}Edit Profil{% endblock title %}



{% block content %}
<center>
    <h1>Edit Profile</h1>
    <form action="/action_page.php">
        <label for="fname">Email:</label><br>
        <input type="text"><br>
        <label for="fname">Password:</label><br>
        <input type="text"><br>
        <label for="fname">NPWP:</label><br>
        <input type="text"><br>
        <label for="fname">Nama:</label><br>
        <input type="text"><br>
        <input type="submit" value="Submit" href="{% url 'blue:ProfilPerusahaan'}">
    </form>
</center>
{% endblock content %}

blue/templates/blue/profilIndividu.html
{% extends 'base.html' %}

{% block title %}Profil{% endblock title %}



{% block content %}
<center>
    <h1>Profil</h1>
    <table style="width:50%">
        <tr>
            <th>Email</th>
            <td>{{ profile.email }}</td>
        </tr>
        <tr>
            <th>Password</th>
            <td>{{ passw.password }}</td>
        </tr>
        <tr>
            <th>NPWP</th>
            <td>{{ organizer.npwp}}</td>
        </tr>
        <tr>
            <th>Nomor KTP</th>
            <td>{{ profile.no_ktp}}</td>
        </tr>
        <tr>
            <th>Nama Depan</th>
            <td>{{ profile.nama_depan }}</td>
        </tr>
        <tr>
            <th>Nama Belakang</th>
            <td>{{ profile.nama_belakang }}</td>
        </tr>
        <tr>
            <th></th>
            <td></td>
        </tr>
        <tr>
            <th></th>
            <td></td>
        </tr>
        <tr>
            <th></th>
            <td><button href="{% url 'blue:editProfilIndividu'}">Edit</button></td>
        </tr>
    </table>
</center>

{% endblock content %}

blue/templates/blue/profilPengunjung.html
{% extends 'base.html' %}

{% block title %}Profil{% endblock title %}



{% block content %}
<center>
    <h1>Profil</h1>
    <table style="width:50%">
        <tr>
            <th>Email</th>
            <td>{{ profile.email }}</td>
        </tr>
        <tr>
            <th>Password</th>
            <td>{{ passw.password }}</td>
        </tr>
        <tr>
            <th>Nama Depan</th>
            <td>{{ profile.nama_depan }}</td>
        </tr>
        <tr>
            <th>Nama Belakang</th>
            <td>{{ profile.nama_belakang }}</td>
        </tr>
        <tr>
            <th></th>
            <td></td>
        </tr>
        <tr>
            <th></th>
            <td></td>
        </tr>
        <tr>
            <th></th>
            <td><button href="{% url 'blue:editProfilPengunjung'}">Edit</button></td>
        </tr>
    </table>
    <a  href="{% url 'blue:dompetDigital'}">
        <p>Cek Dompet</p>
    </a>
</center>

{% endblock content %}

blue/templates/blue/profilPerusahaan.html
{% extends 'base.html' %}

{% block title %}Profil{% endblock title %}



{% block content %}
<center>
    <h1>Profil</h1>
    <table style="width:50%">
        <tr>
            <th>Email</th>
            <td>{{ profile.email }}</td>
        </tr>
        <tr>
            <th>Password</th>
            <td>{{ passw.password }}</td>
        </tr>
        <tr>
            <th>NPWP</th>
            <td>{{ organizer.npwp}}</td>
        </tr>
        <tr>
            <th>Nama</th>
            <td>{{ profile.nama }}</td>
        </tr>
        <tr>
            <th></th>
            <td></td>
        </tr>
        <tr>
            <th></th>
            <td></td>
        </tr>
        <tr>
            <th></th>
            <td><button href="{% url 'blue:editProfilPerusahaan'}">Edit</button></td>
        </tr>
    </table>
</center>

{% endblock content %}

blue/templates/blue/tambahSaldo.html
{% extends 'base.html' %}

{% block title %}Tambah Saldo{% endblock title %}



{% block content %}
<center>
    <h1>Tambah Saldo</h1>
    <table style="width:50%">
        <tr>
            <th>Saldo sekarang: </th>
            <td>Rp8.050.000</td>
        </tr>
    </table>
    <form action="/action_page.php">
        <label for="fname">Tambahkan:</label><br>
        <input type="text"><br><br>
        <input type="submit" value="Submit" href="{% url 'blue:dompetDigital'}">
    </form>
</center>
{% endblock content %}